# -*- coding: utf-8 -*-
"""LSA_2026_data_extraction_and_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15FKWr5dY1y8iPV0nMFXO83ToG3xHF9T9
"""

# Install with the working build backend specification
#!pip install git+https://github.com/YannickJadoul/Parselmouth.git --config-settings="--build-option=--cmake-executable=/usr/bin/cmake"

#!pip install --upgrade praat-parselmouth
#!pip install textgrid

import os
import glob
import parselmouth
import re
import textgrid as tg
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from collections import defaultdict





def get_pitch_window(sound):
    """
    Restructured to process by phrases first, creating optimized pitch objects
    for each phrase segment before extracting F0 measurements.
    """

    # Initial pitch analysis for quantile calculation (same as before)
    pitch = parselmouth.praat.call(sound, "To Pitch (filtered ac)", 0.01,    # time_step
                                                                      50,      # pitch_floor
                                                                      800,     # pitch_ceiling
                                                                      15,      # max_number_of_candidates
                                                                      False,   # very_accurate
                                                                      0.03,    # silence_threshold
                                                                      0.09,
                                                                      0.4,     # voicing_threshold
                                                                      0.055,    # octave_cost
                                                                      0.35,    # octave_jump_cost
                                                                      0.14)    # voiced_unvoiced_cost

    #pitch = parselmouth.praat.call(sound, "To Pitch (ac)", 0.01,    # time_step
    #                                                                  50,      # pitch_floor
    #                                                                  15,      # max_number_of_candidates
    #                                                                  False,   # very_accurate
    #                                                                  0.03,    # silence_threshold
    #                                                                  0.4,     # voicing_threshold
    #                                                                  0.055,    # octave_cost
    #                                                                  0.35,    # octave_jump_cost
    #                                                                  0.14,   # voiced_unvoiced_cost
    #                                                                  800     # pitch_ceiling
    #                               )


    pitch_values = pitch.selected_array["frequency"]

    # Calculate quantiles for pitch floor/ceiling (same as before)
    praat_q35 = parselmouth.praat.call(pitch, "Get quantile", 0, 0, 0.35, "Hertz")
    praat_q65 = parselmouth.praat.call(pitch, "Get quantile", 0, 0, 0.65, "Hertz")
    q35 = np.nanpercentile(pitch_values, 35)
    q65 = np.nanpercentile(pitch_values, 65)

    print("praat q35", praat_q35)
    print("praat q65", praat_q65)
    print("numpy q35", q35)
    print("numpy q65", q65)

    sound_seg_floor = (praat_q35*0.72)-10
    if sound_seg_floor <= 0:
        sound_seg_floor = 50
    sound_seg_ceiling = (praat_q65*1.9)+10
    print(f"Pitch floor: {sound_seg_floor}, ceiling: {sound_seg_ceiling}")

def get_pitch_dynamics_for_segs(sound, textgrid, speaker, num_of_measurements):
    """
    Restructured to process by phrases first, creating optimized pitch objects
    for each phrase segment before extracting F0 measurements.
    """

    # Initial pitch analysis for quantile calculation (same as before)
    pitch = parselmouth.praat.call(sound, "To Pitch (filtered ac)", 0.01,    # time_step
                                                                      50,      # pitch_floor
                                                                      800,     # pitch_ceiling
                                                                      15,      # max_number_of_candidates
                                                                      False,   # very_accurate
                                                                      0.03,    # silence_threshold
                                                                      0.09,
                                                                      0.4,     # voicing_threshold
                                                                      0.055,    # octave_cost
                                                                      0.35,    # octave_jump_cost
                                                                      0.14)    # voiced_unvoiced_cost
    """
    pitch = parselmouth.praat.call(sound, "To Pitch (ac)", 0.01,    # time_step
                                                                      50,      # pitch_floor
                                                                      15,      # max_number_of_candidates
                                                                      False,   # very_accurate
                                                                      0.03,    # silence_threshold
                                                                      0.4,     # voicing_threshold
                                                                      0.055,    # octave_cost
                                                                      0.35,    # octave_jump_cost
                                                                      0.14,   # voiced_unvoiced_cost
                                                                      800     # pitch_ceiling
                                   )

    """
    pitch_values = pitch.selected_array["frequency"]

    # Calculate quantiles for pitch floor/ceiling (same as before)
    praat_q35 = parselmouth.praat.call(pitch, "Get quantile", 0, 0, 0.35, "Hertz")
    praat_q65 = parselmouth.praat.call(pitch, "Get quantile", 0, 0, 0.65, "Hertz")
    q35 = np.nanpercentile(pitch_values, 35)
    q65 = np.nanpercentile(pitch_values, 65)

    print("praat q35", praat_q35)
    print("praat q65", praat_q65)
    print("numpy q35", q35)
    print("numpy q65", q65)

    sound_seg_floor = (praat_q35*0.72)-10
    if sound_seg_floor <= 0:
        sound_seg_floor = 50
    sound_seg_ceiling = (praat_q65*1.9)+10
    print(f"Pitch floor: {sound_seg_floor}, ceiling: {sound_seg_ceiling}")

    # Find tier positions (same as before)
    seg_tier_num = None
    syll_tier_num = None
    morph_tier_num = None
    gloss_tier_num = None
    word_tier_num = None
    phrase_tier_num = None
    sentence_tier_num = None

    for tier_num, tier in enumerate(textgrid):
        if tier.name.lower() == "seg":
            seg_tier_num = tier_num
        if tier.name.lower() == "syll":
            syll_tier_num = tier_num
        if tier.name.lower() == "morph":
            morph_tier_num = tier_num
        if tier.name.lower() == "gloss":
            gloss_tier_num = tier_num
        if tier.name.lower() == "word":
            word_tier_num = tier_num
        if tier.name.lower() == "phrase":
            phrase_tier_num = tier_num
        if tier.name.lower() == "sentence":
            sentence_tier_num = tier_num
        if tier.name.lower() not in ["seg", "syll", "morph", "gloss", "word", "phrase"]:
          print(tier_num, tier.name, sound.name)

    print(f"seg_tier_num: {seg_tier_num}")
    print(f"syll_tier_num: {syll_tier_num}")
    print(f"morph_tier_num: {morph_tier_num}")
    print(f"gloss_tier_num: {gloss_tier_num}")
    print(f"word_tier_num: {word_tier_num}")
    print(f"phrase_tier_num: {phrase_tier_num}")

    measurements = []

    for sent_num, sent_interval in enumerate(textgrid[sentence_tier_num]):
      prev_sent = None
      next_sent = None
      seg_num_in_sentence = 0
      syll_num_in_sentence = 0
      word_num_in_sentence = 0
      phrase_num_in_sentence = 0


      if sent_interval.mark == "" or sent_interval.mark == "PAU":
        continue


      sent_sound = sound.extract_part(
          from_time=sent_interval.minTime,
          to_time=sent_interval.maxTime,
          preserve_times=True  # Keep original time stamps
      )

      # Create phrase-specific pitch object with 15 Hz bandwidth smoothing
      sent_pitch = parselmouth.praat.call(sent_sound, "To Pitch (filtered ac)",
                                              0.01,                    # time_step
                                              sound_seg_floor,         # pitch_floor
                                              sound_seg_ceiling,       # pitch_ceiling
                                              15,                      # max_number_of_candidates
                                              False,                   # very_accurate
                                              0.03,                    # silence_threshold
                                              0.09,                    # voicing_threshold
                                              0.4,                     # voicing_threshold
                                              0.055,                   # octave_cost
                                              0.35,                    # octave_jump_cost
                                              0.14)                    # voiced_unvoiced_cost

      """
      sent_pitch = parselmouth.praat.call(sent_sound, "To Pitch (ac)", 0.01,    # time_step
                                                                      sound_seg_floor,      # pitch_floor
                                                                      15,      # max_number_of_candidates
                                                                      False,   # very_accurate
                                                                      0.03,    # silence_threshold
                                                                      0.4,     # voicing_threshold
                                                                      0.055,    # octave_cost
                                                                      0.35,    # octave_jump_cost
                                                                      0.14, # voiced_unvoiced_cost
                                                                      sound_seg_ceiling     # pitch_ceiling
                                   )


      """
      sent_pitch_smoothed = parselmouth.praat.call(sent_pitch, "Smooth", 15.0)

      num_of_segs_in_sent = 0
      for seg_num_sent, seg_interval_sent in enumerate(textgrid[seg_tier_num]):
        if seg_interval_sent.minTime >= sent_interval.minTime and seg_interval_sent.maxTime <= sent_interval.maxTime:
          num_of_segs_in_sent += 1

      num_of_sylls_in_sent = 0
      for syll_num_sent, syll_interval_sent in enumerate(textgrid[syll_tier_num]):
        if syll_interval_sent.minTime >= sent_interval.minTime and syll_interval_sent.maxTime <= sent_interval.maxTime:
          num_of_sylls_in_sent += 1

      num_of_words_in_sent = 0
      for word_num_sent, word_interval_sent in enumerate(textgrid[word_tier_num]):
        if word_interval_sent.minTime >= sent_interval.minTime and word_interval_sent.maxTime <= sent_interval.maxTime:
          num_of_words_in_sent += 1

      num_of_phrases_in_sent = 0
      for phrase_num_sent, phrase_interval_sent in enumerate(textgrid[phrase_tier_num]):
        if phrase_interval_sent.minTime >= sent_interval.minTime and phrase_interval_sent.maxTime <= sent_interval.maxTime:
          num_of_phrases_in_sent += 1

      for phrase_num, phrase_interval in enumerate(textgrid[phrase_tier_num]):
        prev_phrase = None
        next_phrase = None
        word_num_in_phrase = 0
        syll_num_in_phrase = 0
        seg_num_in_phrase = 0

        if phrase_interval.minTime >= sent_interval.minTime and phrase_interval.maxTime <= sent_interval.maxTime:
          if phrase_interval.mark == "" or "PAU" in phrase_interval.mark or "FS" in phrase_interval.mark or "SpErr" in phrase_interval.mark:
            continue
          phrase_num_in_sentence += 1

          num_of_words_in_phrase = 0
          for word_num_phrase, word_interval_phrase in enumerate(textgrid[word_tier_num]):
            if word_interval_phrase.minTime >= phrase_interval.minTime and word_interval_phrase.maxTime <= phrase_interval.maxTime:
              num_of_words_in_phrase += 1

          num_of_sylls_in_phrase = 0
          for syll_num_phrase, syll_interval_phrase in enumerate(textgrid[syll_tier_num]):
            if syll_interval_phrase.minTime >= phrase_interval.minTime and syll_interval_phrase.maxTime <= phrase_interval.maxTime:
              num_of_sylls_in_phrase += 1

          num_of_segs_in_phrase = 0
          for seg_num_phrase, seg_interval_phrase in enumerate(textgrid[seg_tier_num]):
            if syll_interval_phrase.minTime >= phrase_interval.minTime and seg_interval_phrase.maxTime <= phrase_interval.maxTime:
              num_of_segs_in_phrase += 1


          for word_num, word_interval in enumerate(textgrid[word_tier_num]):
            prev_word = None
            next_word = None


            syll_num_in_word = 0
            seg_num_in_word = 0
            if word_interval.minTime >= phrase_interval.minTime and word_interval.maxTime <= phrase_interval.maxTime:
              if word_interval.mark == "" or "PAU" in word_interval.mark: #should exclude pauses from count
                continue

              word_num_in_sentence += 1 # do I want to include pauses in these counts?
              word_num_in_phrase += 1


              word_syll_lst = []
              num_of_sylls_in_word = 0
              for syll_num_word, syll_interval_word in enumerate(textgrid[syll_tier_num]):
                if syll_interval_word.minTime >= word_interval.minTime and syll_interval_word.maxTime <= word_interval.maxTime:
                  num_of_sylls_in_word += 1
                  word_syll_lst.append(syll_interval_word.mark)
              word_syll_structure = '.'.join(word_syll_lst)


              num_of_segs_in_word = 0
              for seg_num_word, seg_interval_word in enumerate(textgrid[seg_tier_num]):
                if seg_interval_word.minTime >= word_interval.minTime and seg_interval_word.maxTime <= word_interval.maxTime:
                  num_of_segs_in_word += 1




              for syll_num, syll_interval in enumerate(textgrid[syll_tier_num]):
                prev_syll = None
                next_syll = None
                seg_num_in_syll = 0
                if syll_interval.minTime >= word_interval.minTime and syll_interval.maxTime <= word_interval.maxTime:
                  if syll_interval.mark == "" or "PAU" in syll_interval.mark:
                    continue
                  syll_num_in_sentence += 1
                  syll_num_in_phrase += 1
                  syll_num_in_word += 1
                  word_syll_lst.append(syll_interval.mark)



                  num_of_segs_in_syll = 0
                  for seg_num_syll, seg_interval_syll in enumerate(textgrid[seg_tier_num]):
                    if seg_interval_syll.minTime >= syll_interval.minTime and seg_interval_syll.maxTime <= syll_interval.maxTime:
                      num_of_segs_in_syll += 1

                  for seg_num, seg in enumerate(textgrid[seg_tier_num]):
                    prev_seg = None
                    next_seg = None
                    seg_measurements = []
                    seg_info = []
                    if seg.mark == "" or "PAU" in seg.mark:
                      continue
                    else:

                      if seg.minTime >= syll_interval.minTime and seg.maxTime <= syll_interval.maxTime:
                        seg_num_in_sentence += 1
                        seg_num_in_phrase += 1
                        seg_num_in_word += 1
                        seg_num_in_syll += 1

                        seg_id = seg.mark
                        seg_start = seg.minTime
                        seg_end = seg.maxTime
                        seg_duration = seg_end - seg_start

                        seg_info.append(seg_id) # 0 seg id
                        seg_info.append(seg_start) # 1 start time
                        seg_info.append(seg_end) # 2 end time
                        seg_info.append(seg_duration) # 3 seg duration
                        seg_info.append(seg_num_in_syll) # 4 seg number in syllable
                        seg_info.append(seg_num_in_word) # 5 seg number in word
                        seg_info.append(seg_num_in_phrase) # 6 seg number in phrase
                        seg_info.append(seg_num_in_sentence) # 7 seg number in sentence

                        if prev_seg == None:
                          if seg_num > 0:
                            prev_seg = textgrid[seg_tier_num][seg_num - 1].mark
                            prev_seg_duration = textgrid[seg_tier_num][seg_num - 1].maxTime - textgrid[seg_tier_num][seg_num - 1].minTime

                        if next_seg == None:
                          if seg_num < len(textgrid[seg_tier_num]) - 1:
                            next_seg = textgrid[seg_tier_num][seg_num + 1].mark
                            next_seg_start = textgrid[seg_tier_num][seg_num + 1].minTime
                            next_seg_end = textgrid[seg_tier_num][seg_num + 1].maxTime
                            next_seg_duration = textgrid[seg_tier_num][seg_num + 1].maxTime - textgrid[seg_tier_num][seg_num + 1].minTime

                        if prev_syll == None:
                          if syll_num > 0:
                            prev_syll = textgrid[syll_tier_num][syll_num - 1].mark
                            prev_syll_duration = textgrid[syll_tier_num][syll_num - 1].maxTime - textgrid[syll_tier_num][syll_num - 1].minTime

                        if next_syll == None:
                          if syll_num < len(textgrid[syll_tier_num]) - 1:
                            next_syll = textgrid[syll_tier_num][syll_num + 1].mark
                            next_syll_start = textgrid[syll_tier_num][syll_num + 1].minTime
                            next_syll_end = textgrid[syll_tier_num][syll_num + 1].maxTime
                            next_syll_duration = textgrid[syll_tier_num][syll_num + 1].maxTime - textgrid[syll_tier_num][syll_num + 1].minTime

                        if prev_word == None:
                          if word_num > 0:
                            prev_word = textgrid[word_tier_num][word_num - 1].mark
                            prev_word_duration = textgrid[word_tier_num][word_num - 1].maxTime - textgrid[word_tier_num][word_num - 1].minTime

                        if next_word == None:
                          if word_num < len(textgrid[word_tier_num]) - 1:
                            next_word = textgrid[word_tier_num][word_num + 1].mark
                            next_word_start = textgrid[word_tier_num][word_num + 1].minTime
                            next_word_end = textgrid[word_tier_num][word_num + 1].maxTime
                            next_word_duration = textgrid[word_tier_num][word_num + 1].maxTime - textgrid[word_tier_num][word_num + 1].minTime

                        if prev_phrase == None:
                          if phrase_num > 0:
                            prev_phrase = textgrid[phrase_tier_num][phrase_num - 1].mark
                            prev_phrase_duration = textgrid[phrase_tier_num][phrase_num - 1].maxTime - textgrid[phrase_tier_num][phrase_num - 1].minTime

                        if next_phrase == None:
                          if phrase_num < len(textgrid[phrase_tier_num]) - 1:
                            next_phrase = textgrid[phrase_tier_num][phrase_num + 1].mark
                            next_phrase_start = textgrid[phrase_tier_num][phrase_num + 1].minTime
                            next_phrase_end = textgrid[phrase_tier_num][phrase_num + 1].maxTime
                            next_phrase_duration = textgrid[phrase_tier_num][phrase_num + 1].maxTime - textgrid[phrase_tier_num][phrase_num + 1].minTime

                        if prev_sent == None:
                          if sent_num > 0:
                            prev_sent = textgrid[sentence_tier_num][sent_num - 1]
                            prev_sent_duration = textgrid[sentence_tier_num][sent_num - 1].maxTime - textgrid[sentence_tier_num][sent_num - 1].minTime

                        if next_sent == None:
                          if sent_num < len(textgrid[sentence_tier_num]) - 1:
                            next_sent = textgrid[sentence_tier_num][sent_num + 1].mark
                            next_sent_start = textgrid[sentence_tier_num][sent_num + 1].minTime
                            next_sent_end = textgrid[sentence_tier_num][sent_num + 1].maxTime
                            next_sent_duration = textgrid[sentence_tier_num][sent_num + 1].maxTime - textgrid[sentence_tier_num][sent_num + 1].minTime

                        seg_info.append(prev_seg) # 8 prev seg id
                        seg_info.append(prev_seg_duration) # 9 prev seg duration
                        seg_info.append(next_seg) # 10 next seg id
                        seg_info.append(next_seg_duration) # 11 next seg duration

                        seg_info.append(syll_interval.mark) # 12 syll_id
                        seg_info.append(syll_interval.minTime) # 13 syll_start
                        seg_info.append(syll_interval.maxTime) # 14 syll_end
                        seg_info.append(syll_interval.maxTime - syll_interval.minTime) # 15 syll_duration
                        seg_info.append(syll_num_in_word) # 16 syllable number in word
                        seg_info.append(syll_num_in_phrase) # 17 syllable number in phrase
                        seg_info.append(syll_num_in_sentence) # 18 syllable number in sentence
                        seg_info.append(num_of_segs_in_syll) # 19 total number of segments in syllable

                        seg_info.append(prev_syll) # 20 prev syll id
                        seg_info.append(prev_syll_duration) # 21 prev syll duration
                        seg_info.append(next_syll) # 22 next syll id
                        seg_info.append(next_syll_duration) # 23 next syll duration

                        seg_info.append(word_interval.mark) # 24 word id
                        #word_syll_structure = '.'.join(word_syll_lst)
                        seg_info.append(word_syll_structure) # 25 word_syll_structure
                        seg_info.append(word_interval.minTime) # 26 word start
                        seg_info.append(word_interval.maxTime) # 27 word end
                        seg_info.append(word_interval.maxTime - word_interval.minTime) # 28 word duration
                        seg_info.append(word_num_in_phrase) # 29 word number in phrase
                        seg_info.append(word_num_in_sentence) # 30 word number in sentence
                        seg_info.append(num_of_segs_in_word) # 31 number of segments in the word
                        seg_info.append(num_of_sylls_in_word) # 32 number of syllables in the word

                        seg_info.append(prev_word) # 33 previous word id
                        seg_info.append(prev_word_duration) # 34 previous word duration
                        seg_info.append(next_word) # 35 following word id
                        seg_info.append(next_word_duration) # 36 following word duration

                        seg_info.append(phrase_interval.mark) # 37 phrase id
                        seg_info.append(phrase_interval.minTime) # 38 phrase start
                        seg_info.append(phrase_interval.maxTime) # 39 phrase end
                        seg_info.append(phrase_interval.maxTime - phrase_interval.minTime) # 40 phrase duration
                        seg_info.append(phrase_num_in_sentence) # 41 phrase number in sentence
                        seg_info.append(num_of_segs_in_phrase) # 42 number of segments in phrase
                        seg_info.append(num_of_sylls_in_phrase) # 43 number of syllables in phrase
                        seg_info.append(num_of_words_in_phrase) # 44 number of words in phrase
                        seg_info.append(phrase_num_in_sentence) # 45 phrase number in sentence




                        seg_info.append(prev_phrase) # 46 previous phrase id
                        seg_info.append(prev_phrase_duration) # 47 previous phrase duration
                        seg_info.append(next_phrase) # 48 following phrase id
                        seg_info.append(next_phrase_duration) # 49 following phrase duration

                        seg_info.append(sent_interval.mark) # 50 sentence id
                        seg_info.append(sent_interval.minTime) # 51 sentence start time
                        seg_info.append(sent_interval.maxTime) # 52 sentence end time
                        seg_info.append(sent_interval.maxTime - sent_interval.minTime) # 53 sentence duration
                        seg_info.append(num_of_segs_in_sent) # 54 number of segments in sentence
                        seg_info.append(num_of_sylls_in_sent) # 55 number of syllables in sentence
                        seg_info.append(num_of_words_in_sent) # 56 number of words in sentence
                        seg_info.append(num_of_phrases_in_sent) # 57 number of phrases in sentence




                        seg_info.append(prev_sent) # 58 previous sentence id
                        seg_info.append(prev_sent_duration) # 59 previous sentence duration
                        seg_info.append(next_sent) # 60 following sentence id
                        seg_info.append(next_sent_duration) # 61 following sentence duration

                        seg_info.append(speaker) # 62 speaker id
                        seg_info.append(sound.name) # 63 file id



                        step_size = seg_duration/num_of_measurements
                        for step in range(num_of_measurements):
                          sample_start = seg_start + (step * step_size)
                          sample_end = sample_start + step_size
                          if sample_end > seg_end:
                            sample_end = seg_end
                          sample_pitch_mean = parselmouth.praat.call(sent_pitch_smoothed, "Get mean", sample_start, sample_end, "Hertz")
                          sample_mid = (sample_end + sample_start) / 2
                          seg_measurements.append(sample_pitch_mean)
                          seg_measurements.append(sample_mid)

                    if len(seg_info) == 64:

                      measurements.append(seg_info + seg_measurements)
                else: #syll
                  continue
            else: #word
                continue

          else: #phrase
            continue






    return measurements


def run_extraction_on_directory(directory_path, variable_names=None, num_of_measurements=9):
  if variable_names == None:
    variable_names = ["SEG_ID", "SEG_START", "SEG_END", "SEG_DURATION", "SEG_NUM_IN_SYLL", "SEG_NUM_IN_WORD", "SEG_NUM_IN_PHRASE", "SEG_NUM_IN_SENTENCE",
                      "PREV_SEG_ID", "PREV_SEG_DURATION", "NEXT_SEG_ID", "NEXT_SEG_DURATION",
                      "SYLL_ID", "SYLL_START", "SYLL_END", "SYLL_DURATION", "SYLL_NUM_IN_WORD", "SYLL_NUM_IN_PHRASE", "SYLL_NUM_IN_SENTENCE", "NUM_OF_SEGS_IN_SYLL",
                      "PREV_SYLL_ID", "PREV_SYLL_DURATION", "NEXT_SYLL_ID", "NEXT_SYLL_DURATION",
                      "WORD_ID", "WORD_SYLL_STRUCTURE", "WORD_START", "WORD_END", "WORD_DURATION", "WORD_NUM_IN_PHRASE", "WORD_NUM_IN_SENTENCE", "NUM_OF_SEGS_IN_WORD", "NUM_OF_SYLLS_IN_WORD",
                      "PREV_WORD_ID", "PREV_WORD_DURATION", "NEXT_WORD_ID",  "NEXT_WORD_DURATION",
                      "PHRASE_ID", "PHRASE_START", "PHRASE_END", "PHRASE_DURATION", "PHRASE_NUM_IN_SENTENCE", "NUM_OF_SEGS_IN_PHRASE", "NUM_OF_SYLLS_IN_PHRASE", "NUM_OF_WORDS_IN_PHRASE",
                      "PHRASE_NUM_IN_SENTENCE", "PREV_PHRASE_ID", "PREV_PHRASE_DURATION", "NEXT_PHRASE_ID", "NEXT_PHRASE_DURATION",
                      "SENTENCE_ID", "SENTENCE_START", "SENTENCE_END", "SENTENCE_DURATION", "NUM_OF_SEGS_IN_SENTNENCE", "NUM_OF_SYLLS_IN_SENTENCE", "NUM_OF_WORDS_IN_SENTENCE",
                      "NUM_OF_PHRASES_IN_SENTENCE", "PREV_SENTENCE_ID", "PREV_SENTENCE_DURATION", "NEXT_SENTENCE_ID", "NEXT_SENTENCE_DURATION",
                      "SPEAKER_ID", "FILE_ID"
                      ]
  wav_files = []
  tg_files = []
  for wav_file in glob.glob(f"{directory_path}/*.wav"):
    wav_files.append(wav_file)
    for tg_file in glob.glob(f"{directory_path}/*.TextGrid"):
      if wav_file[:-4].replace('.', '_') == tg_file.split(".")[0]:
        tg_files.append(tg_file)


  print(wav_files)
  print(tg_files)

  info = []


  for wf, tf in zip(wav_files, tg_files):
    print(wf)
    print(tf)
    s = None
    t = None
    speaker = None
    t = tg.TextGrid.fromFile(tf)
    if tf.split("_")[-1].split(".")[0] in ["AL", "ES", "EC"]:
      speaker = tf.split("_")[-1].split(".")[0]
    elif int(tf.split("_")[-1].split(".")[0]) == 1966: #I need to check to see which of the Vihman tapes are actually AL files
      speaker = "AL"
    elif int(tf.split("_")[-1].split(".")[0]) >= 1979 and int(tf.split("_")[-1].split(".")[0]) <= 1995:
      speaker = "EC"
    elif int(tf.split("_")[-1].split(".")[0]) >= 1995:
      speaker = "ES"
    else:
      speaker = "Unkown"
    for tier in t:
      if tier.name == "phrase":
        for interval in tier:
          print(interval)
    s = parselmouth.Sound(wf)
    if s.n_channels > 1:
      s = s.convert_to_mono()
    s.name = wf.split("/")[-1].split(".")[0]
    #t = tg.TextGrid.fromFile(tf)
    extracted_info = get_pitch_dynamics_for_segs(s, t, speaker, num_of_measurements)
    #info.append(pitch_info)
    #for phrase in vowel_pitch_info:
    #  snake_info.append(phrase)

    for phrase in extracted_info:
      info.append(phrase)




    print()
    print('___________')
    print()

  f0_columns = []
  for x in range(num_of_measurements):
    f0_columns.append(f"F0_{x}")
    f0_columns.append(f"F0_MIDPOINT_{x}")

  variable_names = variable_names + f0_columns

  measurement_df = pd.DataFrame(info, columns=variable_names)

  return measurement_df



def z_score_normalize_f0(df, group_by, num_of_measurements):
    """
    Z-score normalize F0 columns by speaker using all F0 values per speaker,
    preserving NaN values for time alignment
    """
    z_scored_df = df.copy()

    f0_columns = [f'F0_{i}' for i in range(num_of_measurements)]

    # DETAILED VERSION: Calculate speaker statistics from ALL F0 measurements
    group_stats = {}

    for group in z_scored_df[group_by].unique():
        group_df = z_scored_df[z_scored_df[group_by] == group]

        # Collect all valid F0 values for this speaker across all F0 columns
        all_f0_values = []
        for col in f0_columns:
            if col in group_df.columns:
                valid_values = group_df[col].dropna()  # Remove NaN for stats calculation
                valid_values = valid_values[valid_values > 0]  # Remove 0 or negative F0
                all_f0_values.extend(valid_values.tolist())

        if len(all_f0_values) > 1:
            group_stats[group] = {
                'mean': np.mean(all_f0_values),
                'std': np.std(all_f0_values),
                'n_measurements': len(all_f0_values)
            }
            print(f"Group {group}: mean={group_stats[group]['mean']:.1f}Hz, "
                  f"std={group_stats[group]['std']:.1f}Hz, "
                  f"n={group_stats[group]['n_measurements']}")

    # Apply normalization to each F0 column, keeping NaN values as NaN
    for col in f0_columns:
        if col in z_scored_df.columns:
            normalized_col = f'{col}_ZSCORE'

            # Initialize with NaN (preserves original NaN pattern)
            z_scored_df[normalized_col] = np.nan

            for group in group_stats.keys():
                if group_stats[group]['std'] > 0:
                    # Create mask for valid values for this speaker
                    group_mask = z_scored_df[group_by] == group
                    valid_mask = z_scored_df[col].notna() & (z_scored_df[col] > 0)  # Not NaN and > 0
                    mask = group_mask & valid_mask

                    # Apply z-score normalization using speaker's overall stats
                    z_scored_df.loc[mask, normalized_col] = (
                        (z_scored_df.loc[mask, col] - group_stats[group]['mean']) /
                        group_stats[group]['std']
                    )
                    # NaN values remain NaN automatically

    return z_scored_df, group_stats



def clean_f0_from_non_sonorant_consonants(df, non_sonorant_consonants=None, num_of_measurements=20):
  if non_sonorant_consonants == None:
    non_sonorant_consonants = ["b", "p", "ph", "p'", "d", "t", "th", "t'", "T", "Th", "T'", "k", "kh", "k'"
                           "ts", "ts'", "j", "ch", "ch'", "s", "s'", "sh", "x",
                           "?", "h"]

  clean_df = df.copy()

  clean_df.loc[clean_df["SEG_ID"].str.split("[_+]", regex=True).str[0].isin(non_sonorant_consonants), ["F0_0", "F0_1", "F0_2", "F0_3", "F0_4", "F0_5",
                                                                                "F0_6", "F0_7", "F0_8"]] = np.nan

  # Create a mask for rows where previous segment is non-sonorant
  prev_non_sonorant_mask = clean_df["PREV_SEG_ID"].str.split("_+", regex=True).str[0].isin(non_sonorant_consonants)

  # For each F0 measurement point, check if it's within 10ms of the previous segment end
  for i in range(num_of_measurements):  # F0_0 through F0_8
      f0_col = f"F0_{i}"
      midpoint_col = f"F0_MIDPOINT_{i}"

      # Calculate distance from F0 timepoint to previous segment end (in ms)
      time_distance = clean_df[midpoint_col] - clean_df["SEG_START"]

      # Set to NaN if: (1) previous segment is non-sonorant AND (2) within 10ms
      within_10ms = time_distance <= 0.01

      clean_df.loc[prev_non_sonorant_mask & within_10ms, f0_col] = np.nan


  # Create a mask for rows where previous segment is non-sonorant
  next_non_sonorant_mask = clean_df["NEXT_SEG_ID"].str.split("_+", regex=True).str[0].isin(non_sonorant_consonants)

  # For each F0 measurement point, check if it's within 10ms of the previous segment end
  for i in range(num_of_measurements):  # F0_0 through F0_num_of_measurements-1
      f0_col = f"F0_{i}"
      midpoint_col = f"F0_MIDPOINT_{i}"

      # Calculate distance from F0 timepoint to previous segment end (in ms)
      time_distance = clean_df["SEG_END"] - clean_df[midpoint_col]

      # Set to NaN if: (1) previous segment is non-sonorant AND (2) within 10ms
      within_10ms = time_distance <= 0.01

      clean_df.loc[next_non_sonorant_mask & within_10ms, f0_col] = np.nan
  return clean_df

def remove_outlier_f0(df, num_of_measurements):
  remove_df = df.copy()
  #remove outliers
  for i in range(num_of_measurements):
      outlier_mask = remove_df[f"F0_{i}_ZSCORE"].abs() > 2.5
      n_outliers = outlier_mask.sum()
      print(f"F0_{i}: removing {n_outliers} outliers")
      remove_df.loc[outlier_mask, [f"F0_{i}", f"F0_{i}_ZSCORE"]] = np.nan
  return remove_df



#Add syllable position in word
def add_syll_position_info(df):
  df["SYLL_POS_IN_WORD"] = ["O" if SYLL_NUM_IN_WORD == 1 and NUM_OF_SYLLS_IN_WORD == 1
                            else "I" if SYLL_NUM_IN_WORD == 1 and SYLL_NUM_IN_WORD < NUM_OF_SYLLS_IN_WORD
                            else "F" if SYLL_NUM_IN_WORD > 1 and SYLL_NUM_IN_WORD == NUM_OF_SYLLS_IN_WORD
                            else "M"
                            for SYLL_NUM_IN_WORD, NUM_OF_SYLLS_IN_WORD in zip(df["SYLL_NUM_IN_WORD"], df["NUM_OF_SYLLS_IN_WORD"])]

  #Add syllable position in phrase
  df["SYLL_POS_IN_PHRASE"] = ["O" if SYLL_NUM_IN_PHRASE == 1 and SYLL_NUM_IN_PHRASE == NUM_OF_SYLLS_IN_PHRASE
                            else "I" if SYLL_NUM_IN_PHRASE == 1 and SYLL_NUM_IN_PHRASE < NUM_OF_SYLLS_IN_PHRASE
                            else "F" if SYLL_NUM_IN_PHRASE > 1 and SYLL_NUM_IN_PHRASE == NUM_OF_SYLLS_IN_PHRASE
                            else "M"
                            for SYLL_NUM_IN_PHRASE, NUM_OF_SYLLS_IN_PHRASE in zip(df["SYLL_NUM_IN_PHRASE"], df["NUM_OF_SYLLS_IN_PHRASE"])]

    #Add syllable position in sentence
  df["SYLL_POS_IN_SENTENCE"] = ["O" if SYLL_NUM_IN_SENTENCE == 1 and SYLL_NUM_IN_SENTENCE == NUM_OF_SYLLS_IN_SENTENCE
                            else "I" if SYLL_NUM_IN_SENTENCE == 1 and SYLL_NUM_IN_SENTENCE < NUM_OF_SYLLS_IN_SENTENCE
                            else "F" if SYLL_NUM_IN_SENTENCE > 1 and SYLL_NUM_IN_SENTENCE == NUM_OF_SYLLS_IN_SENTENCE
                            else "M"
                            for SYLL_NUM_IN_SENTENCE, NUM_OF_SYLLS_IN_SENTENCE in zip(df["SYLL_NUM_IN_SENTENCE"], df["NUM_OF_SYLLS_IN_SENTENCE"])]

  return df
#Add word position in phrase
def add_word_position_info(df):
  df["WORD_POS_IN_PHRASE"] = ["O" if WORD_NUM_IN_PHRASE == 1 and WORD_NUM_IN_PHRASE == NUM_OF_WORDS_IN_PHRASE
                            else "I" if WORD_NUM_IN_PHRASE == 1 and WORD_NUM_IN_PHRASE < NUM_OF_WORDS_IN_PHRASE
                            else "F" if WORD_NUM_IN_PHRASE > 1 and WORD_NUM_IN_PHRASE == NUM_OF_WORDS_IN_PHRASE
                            else "M"
                            for WORD_NUM_IN_PHRASE, NUM_OF_WORDS_IN_PHRASE in zip(df["WORD_NUM_IN_PHRASE"], df["NUM_OF_WORDS_IN_PHRASE"])]


  df["WORD_POS_IN_SENTENCE"] = ["O" if WORD_NUM_IN_SENTENCE == 1 and WORD_NUM_IN_SENTENCE == NUM_OF_WORDS_IN_SENTENCE
                            else "I" if WORD_NUM_IN_SENTENCE == 1 and WORD_NUM_IN_SENTENCE < NUM_OF_WORDS_IN_SENTENCE
                            else "F" if WORD_NUM_IN_SENTENCE > 1 and WORD_NUM_IN_SENTENCE == NUM_OF_WORDS_IN_SENTENCE
                            else "M"
                            for WORD_NUM_IN_SENTENCE, NUM_OF_WORDS_IN_SENTENCE in zip(df["WORD_NUM_IN_SENTENCE"], df["NUM_OF_WORDS_IN_SENTENCE"])]
  return df



#Add tone info
def add_tone_info(df):

  def assign_tone_by_word(group):
      """Process all syllables in a word and assign tones."""
      # Get unique syllables in order (assuming segments are already ordered)
      syllables = group.drop_duplicates(subset=['FILE_ID', 'SYLL_ID', 'SYLL_NUM_IN_WORD']).sort_values('SYLL_NUM_IN_WORD')

      tones = []
      h_assigned = False

      for idx, row in syllables.iterrows():
          structure = row['SYLL_ID']

          # Rule 1: ':' gets L
          if ':' in structure and structure.lower() != "cv:":
              tones.append('L')
              h_assigned = True

          # Rule 2: 'vv' without ':' gets H
          elif 'vv' in structure.lower() and ':' not in structure:
              tones.append('H')
              h_assigned = True

          # Rule 3: CVC gets H only if no prior heavy syllable
          elif structure.lower() == 'cvc':
              if not h_assigned:
                  tones.append('H')
                  h_assigned = True
              else:
                  tones.append('N')

          # Rule 4: everything else gets N
          else:
              tones.append('N')

      # Create word tone structure string
      word_tone_structure = '.'.join(tones)

      # Map tones back to all segments in the word
      # Create a mapping from syllable position to tone
      syll_to_tone = dict(zip(syllables['SYLL_NUM_IN_WORD'], tones))

      # Assign tone to each segment based on its syllable position
      group['TONE'] = group['SYLL_NUM_IN_WORD'].map(syll_to_tone)
      group['WORD_TONE_STRUCTURE'] = word_tone_structure

      return group

  # Apply to each word
  result_df = (
      df.groupby(['FILE_ID', 'WORD_ID', 'WORD_START', 'WORD_END'], sort=False, group_keys=False)
      .apply(assign_tone_by_word)
  )

  return result_df



def get_word_tone_category(word_tone_structure, num_syllables): #change name to add_word_tone_category
    """
    Extract single tone category from word tone structure.
    Returns 'H' if word has H, 'L' if word has L.
    For all-N words: returns 'H' if >1 syllable, 'N' if 1 syllable.
    """
    if pd.isna(word_tone_structure):
        return None

    if 'H' in word_tone_structure:
        return 'H'
    elif 'L' in word_tone_structure:
        return 'L'
    else:  # All N's
        # Multi-syllable N-only words -> H
        # Single-syllable N-only words -> N
        #return 'H' if num_syllables > 1 else 'N'
        return 'N'

def add_neighboring_tones(df, full=True):
  # Get one row per word with FILE_ID
  word_tones = df.groupby(['FILE_ID', 'WORD_START', 'WORD_END']).agg({
      'WORD_TONE_STRUCTURE': 'first',
      'NUM_OF_SYLLS_IN_WORD': 'first'  # Need this to count syllables
  }).reset_index().sort_values(['FILE_ID', 'WORD_START'])

  # Apply tone category function with number of syllables
  word_tones['WORD_TONE_CAT'] = word_tones.apply(
      lambda row: get_word_tone_category(row['WORD_TONE_STRUCTURE'], row['NUM_OF_SYLLS_IN_WORD']),
      axis=1
  )

  # Shift WITHIN each FILE_ID group
  word_tones['PREV_WORD_TONE'] = word_tones.groupby('FILE_ID')['WORD_TONE_CAT'].shift(1)
  word_tones['NEXT_WORD_TONE'] = word_tones.groupby('FILE_ID')['WORD_TONE_CAT'].shift(-1)

  # Apply the special logic for when PREV/NEXT word has N tone
  # Need to get prev/next word syllable counts for this
  word_tones['PREV_NUM_SYLLS'] = word_tones.groupby('FILE_ID')['NUM_OF_SYLLS_IN_WORD'].shift(1)
  word_tones['NEXT_NUM_SYLLS'] = word_tones.groupby('FILE_ID')['NUM_OF_SYLLS_IN_WORD'].shift(-1)

  if full == True:
    # Override PREV_TONE: if previous word had all N's, recode based on syllable count
    word_tones.loc[word_tones['PREV_WORD_TONE'] == 'N', 'PREV_WORD_TONE'] = word_tones.loc[
        word_tones['PREV_WORD_TONE'] == 'N'
    ].apply(lambda row: 'H' if row['PREV_NUM_SYLLS'] > 1 else 'N', axis=1)



    # Override NEXT_TONE: if next word had all N's, use L for multi-syllable, N for single
    word_tones.loc[word_tones['NEXT_WORD_TONE'] == 'N', 'NEXT_WORD_TONE'] = word_tones.loc[
        word_tones['NEXT_WORD_TONE'] == 'N'
    ].apply(lambda row: 'L' if row['NEXT_NUM_SYLLS'] > 1 else 'N', axis=1)

  # Merge back to original dataframe
  df = df.drop(columns=['PREV_WORD_TONE', 'NEXT_WORD_TONE'], errors='ignore')
  df = df.merge(
      word_tones[['FILE_ID', 'WORD_START', 'WORD_END', 'PREV_WORD_TONE', 'NEXT_WORD_TONE']],
      on=['FILE_ID', 'WORD_START', 'WORD_END'],
      how='left'
  )

  # Handle PAU cases
  df.loc[df['PREV_WORD_ID'] == 'PAU', 'PREV_WORD_TONE'] = 'PAU'
  df.loc[df['NEXT_WORD_ID'] == 'PAU', 'NEXT_WORD_TONE'] = 'PAU'

  return df

def add_neighboring_laryngeal_class(df, voiced=None, voiceless=None, aspirated=None, glottalic=None, sonorant=None):
  if voiced == None:
    voiced = ["b", "d", "m", "n", "l", "y", "w"]

  if voiceless == None:
    voiceless = ["p", "t", "T", "k", "s", "sh", "ts", "j"]

  if aspirated == None:
    aspirated = ["ph", "th", "Th", "kh", "x", "ch"]

  if glottalic == None:
    glottalic = ["?", "h", "p'", "t'", "T'", "k'", "ts'", "ch'"]

  if sonorant == None:
    sonorant = []

  df.loc[df["PREV_SEG_ID"].str.split("[_+]", regex=True).str[0].isin(voiced), "PREV_LARYNGEAL_CLASS"] = "voiced"
  df.loc[df["PREV_SEG_ID"].str.split("[_+]", regex=True).str[0].isin(voiceless), "PREV_LARYNGEAL_CLASS"] = "voiceless"
  df.loc[df["PREV_SEG_ID"].str.split("[_+]", regex=True).str[0].isin(aspirated), "PREV_LARYNGEAL_CLASS"] = "aspirated"
  df.loc[df["PREV_SEG_ID"].str.split("[_+]", regex=True).str[0].isin(glottalic), "PREV_LARYNGEAL_CLASS"] = "glottalic"
  df.loc[df["PREV_SEG_ID"].str.split("[_+]", regex=True).str[0].isin(sonorant), "PREV_LARYNGEAL_CLASS"] = "sonorant"

  df.loc[df["NEXT_SEG_ID"].str.split("[_+]", regex=True).str[0].isin(voiced), "NEXT_LARYNGEAL_CLASS"] = "voiced"
  df.loc[df["NEXT_SEG_ID"].str.split("[_+]", regex=True).str[0].isin(voiceless), "NEXT_LARYNGEAL_CLASS"] = "voiceless"
  df.loc[df["NEXT_SEG_ID"].str.split("[_+]", regex=True).str[0].isin(aspirated), "NEXT_LARYNGEAL_CLASS"] = "aspirated"
  df.loc[df["NEXT_SEG_ID"].str.split("[_+]", regex=True).str[0].isin(glottalic), "NEXT_LARYNGEAL_CLASS"] = "glottalic"
  df.loc[df["NEXT_SEG_ID"].str.split("[_+]", regex=True).str[0].isin(sonorant), "NEXT_LARYNGEAL_CLASS"] = "sonorant"

  df.loc[(df["NEXT_WORD_ID"] == "PAU") &
        ((df["NEXT_LARYNGEAL_CLASS"].isna()) | (df["NEXT_LARYNGEAL_CLASS"] == "")) , "NEXT_LARYNGEAL_CLASS"] = "PAU"

  return df

def add_vowel_info(df, high=None, mid=None, low=None, front=None, back=None):
  if high==None:
    high = ["i", "i:", "ii", "ii:", "u", "u:", "uu", "uu:"]

  if mid==None:
    mid = ["e", "e:", "ee", "ee:", "o", "o:", "oo", "oo:"]

  if low==None:
    low = ["a", "a:", "aa", "aa:"]

  df.loc[df["SEG_ID"].str.split("[_+]", regex=True).str[0].isin(high), "VOWEL_HEIGHT"] = "high"
  df.loc[df["SEG_ID"].str.split("[_+]", regex=True).str[0].isin(mid), "VOWEL_HEIGHT"] = "mid"
  df.loc[df["SEG_ID"].str.split("[_+]", regex=True).str[0].isin(low), "VOWEL_HEIGHT"] = "low"

  if front==None:
    front = ["i", "i:", "ii", "ii:", "e", "e:", "ee", "ee:"]

  if back==None:
    back = ['a', 'a:', 'aa', 'aa:', "o", "o:", "oo", "oo:", "oo:", "i", "i:", "ii", "ii:", "u", "u:", "uu", "uu:"]

  df.loc[df["SEG_ID"].str.split("[_+]", regex=True).str[0].isin(front), "VOWEL_FRONTNESS"] = "front"
  df.loc[df["SEG_ID"].str.split("[_+]", regex=True).str[0].isin(back), "VOWEL_FRONTNESS"] = "back"

  return df

def get_tone_info_by_seg(df, structure):
  # Method 1: value_counts() - most common
  print(df['TONE'].value_counts())

  # Method 2: with proportions
  print(df['TONE'].value_counts(normalize=True))

  # Method 3: include NaN counts
  print(df['TONE'].value_counts(dropna=False))

  # Method 4: crosstab for multiple columns
  print(pd.crosstab(df['TONE'], df[f'PREV_{structure}_TONE']))

  print(pd.crosstab(df['TONE'], df[f'NEXT_{structure}_TONE']))

  # Method 5: groupby + size
  print(df.groupby('TONE').size())

def get_tone_info_by_word(df, structure):
    # Group by unique words first
    word_df = df.groupby(['WORD_ID', 'PHRASE_ID', 'FILE_ID', 'WORD_START', 'WORD_END']).first().reset_index()

    # 1. Basic count of words by TONE
    print(f"\n{'='*60}")
    print(f"TONE Distribution for {structure} (Unique Words)")
    print(f"{'='*60}")
    print(word_df['TONE'].value_counts().sort_index())

    # 2. With proportions
    print(f"\n{'-'*60}")
    print("TONE Proportions:")
    print(f"{'-'*60}")
    print(word_df['TONE'].value_counts(normalize=True).sort_index())

    # 3. Include NaN counts if any
    print(f"\n{'-'*60}")
    print("TONE with NaN counts:")
    print(f"{'-'*60}")
    print(word_df['TONE'].value_counts(dropna=False).sort_index())

    # 4. Cross-tabulation with PREV tone
    print(f"\n{'-'*60}")
    print(f"TONE vs PREV_{structure}_TONE:")
    print(f"{'-'*60}")
    print(pd.crosstab(word_df['TONE'], word_df[f'PREV_{structure}_TONE'], margins=True))

    # 5. Cross-tabulation with NEXT tone
    print(f"\n{'-'*60}")
    print(f"TONE vs NEXT_{structure}_TONE:")
    print(f"{'-'*60}")
    print(pd.crosstab(word_df['TONE'], word_df[f'NEXT_{structure}_TONE'], margins=True))

    # 6. Groupby size (alternative to value_counts)
    print(f"\n{'-'*60}")
    print("TONE counts (via groupby):")
    print(f"{'-'*60}")
    print(word_df.groupby('TONE').size())

    print(f"\n{'='*60}\n")
